### ISSUE TITLE
Clean up issues from QA of RC on 16 May 2018

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-uganda-hpv#32]
- [x] ID number is not appearing underneath the girl's name in the vaccine widget
- [x] Take photo from profile page is not working. I tap on the avatar and the phone app doesn't launch. I can only take a picture from the reg form or edit reg form
- [x] After giving Dose 2 to dummy child Monday Kamisi, it turned the Dose 2 due alert to grey. Instead, it should have changed immediately to Complete. It changed to complete only later on (after I had registered another girl). To replicate, vaccinate a girl with Dose 2, then return to register screen. The dose column isn't updated correctly to Complete.
- [x] After I registered two new girls (Susie Q and Martha Jane), I noticed that they appeared below Monday Kamisi in the register list. They should have appeared at the top, since they were last updated. (CG update: Actually this might be due to the datetime changes that we're doing for testing the vaccine dose schedules. Can someone confirm?)

**Comment by cagulas** [comment]
Tomorrow I will test the schedules as well as the data syncing to OpenMRS, then I'm done. Good job!

**Comment by cagulas** [comment]
- [ ] Issue with OpenSRP ID 1291103 being reused. ID is currently assigned to child Martha Jane. But each time I open the birth registration form, this ID number is populated.
- [ ] School location is showing up as a long UUID in the address field in OpenMRS - see girl Martha Jane
- [ ] Two girls who I registered are failing to sync to OpenMRS. One of them was registered yesterday. I am getting the sync successful message. Two girls: Susie Q (ID: 1239876543) and Julie Christy (ID: 893838484). I should note that both of these girls, I scanned a new ID using a QR code since I'm having the unique ID issue above and can't register new girls with the pre-generated ID.
- [ ] Parent concept for HPV vaccine not appearing in OpenMRS for dose 1 and 2.
- [ ] D1 encounter not appearing for Akannda Salome in OpenMRS even though it shows she was vaccinated in OpenSRP.
- [ ] The Age is too close to the girl's DOB in reg form when it's not just years, i.e. 9y is fine, but 9y 2m is too close to the DOB
- [ ] Kid not marked as deceased in OpenMRS - should show a banner message for deceased. See kid Monday Kamisi
- [ ] When I updated Stacy Angani's VHT (from blank to Mr. T), I noted it appeared right away in the profile view, but it briefly disappeared before reappearing. To reproduce, register a girl but leave VHT name and number blank. Then go back to edit the form and add the VHT and number. When you return to the profile view it appears, but then it briefly disappears before reappearing again.
- [ ] The picture that I took for Stacy in the edit reg form didn't save either in the app or sync to OpenMRS.
- [ ] Photos and avatars are not syncing appropriately it seems - I see a photo for Monday Kamisi on OpenMRS but not on the phone (I didn't take this one myself); the girl avatar appears for Janette Rembo in OpenMRS for some reason (why is the avatar image syncing?)

**Comment by ndegwamartin** [comment]
@cagulas with reference to the question **why is the avatar image syncing**  , its not syncing, rather its been set as the default image on OpenMRS

**Comment by ndegwamartin** [comment]
It should work for all since it is just a static reference used when no actual image exists. do you have a list of 2 or 3 children for which it doesn't appear? I can use those to troubleshoot

**Comment by cagulas** [comment]
Martha Jane
Stacy Angani

**Comment by ndegwamartin** [comment]
Thanks for those, was able to troubleshoot successfully, appears OpenMRS randomly changes the case of the default image, thus returns the incorrect image when rendering. That is fixed now.

For the registration, there was a constraint of 7 Digits for the identifier , thus ID: 893838484 cant sync successfully since it fails OpenMRS validation

**Comment by cagulas** [comment]
Ok cool, I figured it might have something to do with that.

**Comment by cagulas** [comment]
Lgtm
