### ISSUE TITLE
Create login screen for Uganda HPV

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-uganda-hpv#7]
<img width="454" alt="screen shot 2018-03-07 at 12 38 46 pm" src="https://user-images.githubusercontent.com/3488986/37084916-cab58de6-2204-11e8-8ad3-4f5a1b9845dd.png">

The top right button opens the server url settings menu. It should come pre-populated with the server url for the project.

Please change "Enter password" to just "Password".

The show password option will function the same way as TBR app.

- [x]  Layout structure and View components
- [x]  Add top right settings menu. It should come pre-populated with the server url for the project
- [x]  Add user configurability of View
- [x]  Login/Authentication functional implementation
- [x]  Add offline/local login functionality (After first login)
- [x]  Test/Adapt views render well in both mobile devices (5" min) and tablets

**Comment by cagulas** [comment]
Results from QA on 11th April release:

- [ ] The girl icon looks a bit blurry on my 5-inch J5 phone. Is there a better quality version we can use, or is the issue because it gets rendered too small on my phone?
- [ ] Don't capitalize "Password" in "Show Password"
- [ ] Can we make the check box for show password larger? It's hard for me to tap. We can move the Log in button lower if needed.

**Comment by vincent-karuri** [comment]
Done. Please test.

**Comment by cagulas** [comment]
Do I need an updated apk?

**Comment by vincent-karuri** [comment]
Right, in that case, let me wait and see if Martin has any changes he would like to incorporate into that.

**Comment by cagulas** [comment]
Ok, great, let me know.

**Comment by cagulas** [comment]
Lgtm
